name: 'segment_activity_schema'
version: '0.1.0'
config-version: 2

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  segment_page_views_table: "{{ source('segment_source', 'pages') }}"
